export const ADD_MEMBER = 'ADD_MEMBER'
export const DELETE_MEMBER = 'DELETE_MEMBER'
export const SET_DETAILS = 'SET_DETAILS'
export const SELECT_DETAIL = 'SELECT_DETAIL'
export const SET_PLAY = 'SET_PLAY'
export const SET_LAST = 'SET_LAST'
